from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel
import httpx
import time
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

from guardrails import GuardrailService

# 1. Create our API application
app = FastAPI(title="LLM Monitoring & Security API")

# Initialize Guardrail Service
guardrail_service = GuardrailService()

# Ollama configuration
OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "qwen2.5-coder:7b"

# 2. Define Prometheus Observability Metrics
REQUEST_COUNT = Counter(
    "llm_requests_total",
    "Total number of HTTP requests to LLM API",
    ["model", "status"]
)
SECURITY_VIOLATIONS = Counter(
    "llm_security_violations_total",
    "Total prompt injection attacks blocked by security guardrails"
)
PII_REDACTIONS = Counter(
    "llm_pii_redactions_total",
    "Total count of PII items pseudonymized in user prompts"
)
TOKENS_GENERATED = Counter(
    "llm_tokens_generated_total",
    "Total tokens generated by local LLM models",
    ["model"]
)
REQUEST_LATENCY = Histogram(
    "llm_request_duration_seconds",
    "Total request latency in seconds",
    ["model"]
)


# 3. Request Schema
class ChatRequest(BaseModel):
    prompt: str
    model: str = DEFAULT_MODEL


# 4. Health Check Endpoint
@app.get("/health")
def check_health():
    return {"status": "healthy", "message": "API is running perfectly!"}


# 5. Prometheus Metrics Endpoint
@app.get("/metrics")
def get_metrics():
    """
    Exposes Prometheus time-series metrics to be scraped by Prometheus server.
    """
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


# 6. Chat Endpoint with Security Guardrails & Prometheus Observability
@app.post("/chat")
async def chat_with_ai(request: ChatRequest):
    """
    1. Runs Security Guardrails (Injection check + PII Pseudonymization & Vaulting)
    2. Sends sanitized prompt to local Ollama model
    3. Rehydrates response with original PII
    4. Records Prometheus Observability Metrics
    """
    start_time = time.time()

    # Step A: Run Security Guardrail Inspection
    guardrail = guardrail_service.process_prompt(request.prompt)

    # Block prompt injections immediately
    if not guardrail.is_safe:
        SECURITY_VIOLATIONS.inc()
        REQUEST_COUNT.labels(model=request.model, status="blocked_security").inc()
        raise HTTPException(
            status_code=400,
            detail={
                "error": "Security Violation Detected",
                "message": "Prompt blocked by AI Security Guardrails",
                "violations": guardrail.violations
            }
        )

    # Track PII Redactions
    if guardrail.pii_redacted_count > 0:
        PII_REDACTIONS.inc(guardrail.pii_redacted_count)

    # Step B: Send SANITIZED prompt to Ollama
    payload = {
        "model": request.model,
        "prompt": guardrail.sanitized_prompt,
        "stream": False
    }

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(OLLAMA_URL, json=payload)
            response.raise_for_status()

            data = response.json()
            raw_reply = data.get("response", "")
            target_model = data.get("model", request.model)

            # Step C: Re-hydrate LLM response using Privacy Vault
            rehydrated_reply = guardrail_service.rehydrate(raw_reply, guardrail.vault)

            # Step D: Record Prometheus Observability Metrics
            eval_tokens = data.get("eval_count", 0)
            total_duration_s = data.get("total_duration", 0) / 1e9 if data.get("total_duration") else (time.time() - start_time)

            REQUEST_COUNT.labels(model=target_model, status="success").inc()
            TOKENS_GENERATED.labels(model=target_model).inc(eval_tokens)
            REQUEST_LATENCY.labels(model=target_model).observe(total_duration_s)

            return {
                "model": target_model,
                "reply": rehydrated_reply,
                "security": {
                    "is_safe": True,
                    "prompt_modified": guardrail.sanitized_prompt != request.prompt,
                    "pii_redact_count": guardrail.pii_redacted_count,
                    "sanitized_prompt_sent_to_llm": guardrail.sanitized_prompt,
                    "vault_placeholders": guardrail.vault
                },
                "metrics": {
                    "total_duration_seconds": round(total_duration_s, 3),
                    "load_duration_ns": data.get("load_duration"),
                    "prompt_eval_count": data.get("prompt_eval_count"),
                    "eval_count": eval_tokens
                }
            }

    except httpx.ConnectError:
        REQUEST_COUNT.labels(model=request.model, status="error_503").inc()
        raise HTTPException(
            status_code=503,
            detail="Could not connect to Ollama service. Is Ollama running on port 11434?"
        )
    except Exception as e:
        REQUEST_COUNT.labels(model=request.model, status="error_500").inc()
        raise HTTPException(status_code=500, detail=str(e))
